services:
  app:
    build: .
    restart: always
    ports:
      - "8090:8090"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`events.ryvo.com.br`)"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=lets-encrypt"
      - "traefik.http.services.app.loadbalancer.server.port=8090"
      - "traefik.docker.network=web"

networks:
  web:
    external: true