services:
  events:
    build: .
    restart: always
    pull_policy: build
    ports:
      - "8090:8090"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.events.rule=Host(`events.ryvo.com.br`)"
      - "traefik.http.routers.events.tls=true"
      - "traefik.http.routers.events.tls.certresolver=lets-encrypt"
      - "traefik.http.services.events.loadbalancer.server.port=8090"
      - "traefik.docker.network=web"

networks:
  web:
    external: true